-- Creen sus propias direcciones 

CREATE DIRECTORY DIR_ARCHIVOS as 'C:\Users\elber\OneDrive\Documentos\GitHub\Carlsberg\Fotos';



CREATE OR REPLACE FUNCTION IMPORTAR_BINARIO(NOMBRE VARCHAR2)        -- NO SE SI FUNCIONA CON ARCHIVOS DIFERENTES DE IMAGENES
RETURN BLOB IS                                                              -- FUNCION DEVUELVE LA RUTA DEL ARCHIVO QUE SE QUIERE ALMACENAR EN LA TABLA
	R_BLOB BLOB;
	V_BFILE BFILE := BFILENAME('DIR_ARCHIVOS',NOMBRE);
BEGIN
	DBMS_LOB.CREATETEMPORARY(R_BLOB,true);
	DBMS_LOB.OPEN(V_BFILE,DBMS_LOB.LOB_READONLY);
	DBMS_LOB.LOADFROMFILE(R_BLOB,V_BFILE,DBMS_LOB.GETLENGTH(V_BFILE));
	DBMS_LOB.CLOSE(V_BFILE);
	RETURN R_BLOB;
END;

