-- Creen sus propias direcciones // OJO PARA CREAR EL DIRECTORIO TIENEN QUE ENTRAR COMO USUARIO SYSTEM

CREATE DIRECTORY DIR_ARCHIVOS as 'C:\Users\elber\OneDrive\Documentos\GitHub\Carlsberg\Fotos';



CREATE OR REPLACE FUNCTION IMPORTAR_BINARIO(NOMBRE VARCHAR2)       
RETURN BLOB IS                                                              
	R_BLOB BLOB;
	V_BFILE BFILE := BFILENAME('DIR_ARCHIVOS',NOMBRE);
BEGIN
	DBMS_LOB.CREATETEMPORARY(R_BLOB,true);
	DBMS_LOB.OPEN(V_BFILE,DBMS_LOB.LOB_READONLY);
	DBMS_LOB.LOADFROMFILE(R_BLOB,V_BFILE,DBMS_LOB.GETLENGTH(V_BFILE));
	DBMS_LOB.CLOSE(V_BFILE);
	RETURN R_BLOB;
END;

--- para clob

create or replace FUNCTION FN_IMPORTAR_BINARIO_CLOB(NOMBRE VARCHAR2)        
RETURN CLOB IS                                                             
	R_CLOB CLOB;
	V_BFILE BFILE := BFILENAME('ARCHIVOS',NOMBRE);
BEGIN
	DBMS_LOB.CREATETEMPORARY(R_CLOB,true);
	DBMS_LOB.OPEN(V_BFILE,DBMS_LOB.LOB_READONLY);
	DBMS_LOB.LOADFROMFILE(R_CLOB,V_BFILE,DBMS_LOB.GETLENGTH(V_BFILE));
	DBMS_LOB.CLOSE(V_BFILE);
	RETURN R_CLOB;
END;

