drop table muestra;
drop table procesobasico;
drop table formapago;
drop table datoscuenta;
drop table contacto;
drop table medida;
drop table resultadoevaluacion;
drop table patrocinio;
drop table comida;
drop table resumenhistorico;

CREATE OR REPLACE TYPE MUESTRA AS OBJECT (
   MUES_TIPOBOTELLA     VARCHAR2(30),
   MUES_CAPACIDAD       NUMBER(7) 
);


CREATE OR REPLACE TYPE MUESTRA_NT AS TABLE OF MUESTRA;

CREATE OR REPLACE TYPE RECETAPROCESOBASICO AS OBJECT (
    RPB_ETAPA          VARCHAR2(30) ,
    RPB_ACTIVIDAD      VARCHAR2(30) 
);

CREATE OR REPLACE TYPE RECETAPROCESOBASICO_NT AS TABLE OF RECETAPROCESOBASICO;

CREATE OR REPLACE TYPE FORMAPAGO AS OBJECT (
    FPAGO_TIPO         VARCHAR2(30),
    FPAGO_DESCRIPCION  VARCHAR2(30) ,
    FPAGO_TIEMPOCUOTAS VARCHAR2(30),
    FPAGO_CANTCUOTAS   NUMBER(7),
    FPAGO_DATOSCUENTAS VARCHAR2(30)
);

CREATE OR REPLACE TYPE FORMAPAGO_NT AS TABLE OF FOMA_PAGO;

CREATE OR REPLACE TYPE DATOSCUENTA AS OBJECT (
    DAC_BANCO          VARCHAR2(30) ,
    DAC_NUMCUENTA      NUMBER(7)   ,
    DAC_NOMBRE         VARCHAR2(30) ,
    DAC_TIPOCUENTA     VARCHAR2(30),
    DAC_EMAIL          VARCHAR2(30)   
);

CREATE OR REPLACE TYPE DATOSCUENTA_NT AS TABLE OF DATOSCUENTA;

CREATE OR REPLACE TYPE CONTACTO AS OBJECT (
    CON_NOMBRE         VARCHAR2(30)  ,
    CON_APELLIDO       VARCHAR2(30)   ,
    CON_CARGO          VARCHAR2(30)   ,
    CON_TELEFONO       VARCHAR2(30)    
);

CREATE OR REPLACE TYPE CONTACTO_NT AS TABLE OF CONTACTO;

CREATE OR REPLACE TYPE MEDIDA (
    ME_CANTIDAD        VARCHAR2(30)     ,
    ME_TIPOMEDIDA      VARCHAR2(30)         
);

CREATE OR REPLACE TYPE MEDIDA_NT AS TABLE OF MEDIDA;

CREATE OR REPLACE TYPE RESULTADOEVALUACION AS OBJECT (
    RES_AÑO            DATE                 ,
    RES_RESULTADO      NUMBER(7)               ,
    RES_POSICION       NUMBER(7)               ,
    RES_IDPRODUCTOR    NUMBER(7)              ,
    RED_RUBRO          VARCHAR2(30)           
);

CREATE OR REPLACE TYPE RESULTADOEVALUACION_NT AS TABLE OF RESULTADOEVALUACION;

CREATE OR REPLACE TYPE PATROCINIO AS OBJECT (
    PATROCINIO_NOMBRE  VARCHAR2(30)             ,
    PATROCINIO_DESCRIPCION VARCHAR2(30)        ,
    PATROCINIO_AÑOS    VARCHAR2(30)             
);

CREATE OR REPLACE TYPE PATROCINIO_NT AS TABLE OF PATROCINIO;

CREATE OR REPLACE TYPE COMIDA AS OBJECT (
    CON_NOMBRE         VARCHAR2(30)            ,
    CON_DESCRIPCION    VARCHAR2(30)             
);

CREATE OR REPLACE TYPE COMIDA_NT AS TABLE OF COMIDA;

CREATE OR REPLACE TYPE RESUMENHISTORICO AS OBJECT (
    RE_FECHA           DATE                 ,
    RE_HECHO           VARCHAR2(30)                  
);

CREATE OR REPLACE TYPE RESUMENHISTORICO_NT AS TABLE OF RESUMENHISTORICO;