drop table muestra;
drop table procesobasico;
drop table formapago;
drop table datoscuenta;
drop table contacto;
drop table medida;
drop table resultadoevaluacion;
drop table patrocinio;
drop table comida;
drop table resumenhistorico;

CREATE OR REPLACE TYPE MUESTRA AS OBJECT (
   MUES_TIPOBOTELLA     CHAR(256),
   MUES_CAPACIDAD       NUMBER 
);


CREATE OR REPLACE TYPE MUESTRA_NT AS TABLE OF MUESTRA;

CREATE OR REPLACE TYPE RECETAPROCESOBASICO AS OBJECT (
    RPB_ETAPA          CHAR(256) ,
    RPB_ACTIVIDAD      CHAR(256) 
);

CREATE OR REPLACE TYPE RECETAPROCESOBASICO_NT AS TABLE OF RECETAPROCESOBASICO;

CREATE OR REPLACE TYPE FORMAPAGO AS OBJECT (
    FPAGO_TIPO         CHAR(256),
    FPAGO_DESCRIPCION  CHAR(256) ,
    FPAGO_TIEMPOCUOTAS CHAR(256),
    FPAGO_CANTCUOTAS   NUMBER,
    FPAGO_DATOSCUENTAS CHAR(256)
);

CREATE OR REPLACE TYPE FORMAPAGO_NT AS TABLE OF FOMA_PAGO;

CREATE OR REPLACE TYPE DATOSCUENTA AS OBJECT (
    DAC_BANCO          CHAR(256) ,
    DAC_NUMCUENTA      NUMBER   ,
    DAC_NOMBRE         CHAR(256) ,
    DAC_TIPOCUENTA     CHAR(256),
    DAC_EMAIL          CHAR(256)   
);

CREATE OR REPLACE TYPE DATOSCUENTA_NT AS TABLE OF DATOSCUENTA;

CREATE OR REPLACE TYPE CONTACTO AS OBJECT (
    CON_NOMBRE         CHAR(256)  ,
    CON_APELLIDO       CHAR(256)   ,
    CON_CARGO          CHAR(256)   ,
    CON_TELEFONO       CHAR(256)    
);

CREATE OR REPLACE TYPE CONTACTO_NT AS TABLE OF CONTACTO;

CREATE OR REPLACE TYPE MEDIDA (
    ME_CANTIDAD        CHAR(256)     ,
    ME_TIPOMEDIDA      CHAR(256)         
);

CREATE OR REPLACE TYPE MEDIDA_NT AS TABLE OF MEDIDA;

CREATE OR REPLACE TYPE RESULTADOEVALUACION AS OBJECT (
    RES_AÑO            DATE                 ,
    RES_RESULTADO      NUMBER               ,
    RES_POSICION       NUMBER               ,
    RES_IDPRODUCTOR    NUMBER              ,
    RED_RUBRO          CHAR(256)           
);

CREATE OR REPLACE TYPE RESULTADOEVALUACION_NT AS TABLE OF RESULTADOEVALUACION;

CREATE OR REPLACE TYPE PATROCINIO AS OBJECT (
    PATROCINIO_NOMBRE  CHAR(256)             ,
    PATROCINIO_DESCRIPCION CHAR(256)        ,
    PATROCINIO_AÑOS    CHAR(256)             
);

CREATE OR REPLACE TYPE PATROCINIO_NT AS TABLE OF PATROCINIO;

CREATE OR REPLACE TYPE COMIDA AS OBJECT (
    CON_NOMBRE         CHAR(256)            ,
    CON_DESCRIPCION    CHAR(256)             
);

CREATE OR REPLACE TYPE COMIDA_NT AS TABLE OF COMIDA;

CREATE OR REPLACE TYPE RESUMENHISTORICO AS OBJECT (
    RE_FECHA           DATE                 ,
    RE_HECHO           CHAR(256)                  
);

CREATE OR REPLACE TYPE RESUMENHISTORICO_NT AS TABLE OF RESUMENHISTORICO;