

CREATE OR REPLACE TYPE FOTOS AS OBJECT (
FOTOS       BLOB 
);
/
CREATE OR REPLACE TYPE FOTOS_NT AS TABLE OF FOTOS;
/

-----TDA

CREATE OR REPLACE TYPE MEDIDA AS OBJECT(
    ME_VALOR        VARCHAR2(30)     ,
    ME_UNIDAD      VARCHAR2(30)         
);
/

CREATE OR REPLACE TYPE COMIDA AS OBJECT (
    CON_NOMBRE         VARCHAR2(30)            ,
    CON_DESCRIPCION    VARCHAR2(30)             
);
/
CREATE OR REPLACE TYPE PATROCINIO AS OBJECT (
    PATROCINIO_NOMBRE  VARCHAR2(30)             ,
    PATROCINIO_DESCRIPCION VARCHAR2(30)        ,
    PATROCINIO_AÑOS    VARCHAR2(30)             
);
/

CREATE OR REPLACE TYPE DISTRIBUCION AS OBJECT (
DIS_MES                DATE,
DIS_AÑO                DATE,
DIS_CANTHECTOLITROS    NUMBER(7)
);
/

CREATE OR REPLACE TYPE DATOSCUENTA AS OBJECT (
    DAC_BANCO          VARCHAR2(30) ,
    DAC_NUMCUENTA      NUMBER(7)   ,
    DAC_NOMBRE         VARCHAR2(30) ,
    DAC_TIPOCUENTA     VARCHAR2(30),
    DAC_EMAIL          VARCHAR2(30)   
);
/

---NESTED

CREATE OR REPLACE DATOS_CUENTA_NT AS TABLE OF DATOSCUENTA;
/

---TYPE

CREATE OR REPLACE TYPE FORMAPAGO AS OBJECT (
    FPAGO_TIPO         VARCHAR2(30),
    FPAGO_DESCRIPCION  VARCHAR2(30) ,
    FPAGO_TIEMPOCUOTAS VARCHAR2(30),
    FPAGO_CANTCUOTAS   NUMBER(7),
    FPAGO_DATOSCUENTAS DATOSCUENTA
);   ---->>> NO SE SI SE PUEDE PONER ASI
/

CREATE OR REPLACE TYPE CONTACTO AS OBJECT (
    CON_NOMBRE         VARCHAR2(30)  ,
    CON_APELLIDO       VARCHAR2(30)   ,
    CON_CARGO          VARCHAR2(30)   ,
    CON_TELEFONO       VARCHAR2(30)    
);
/

CREATE OR REPLACE TYPE RECETAPROCESOBASICO AS OBJECT (
    RPB_ETAPA          VARCHAR2(30) ,
    RPB_ACTIVIDAD      VARCHAR2(30) , --- MISMO PROCESO
	RPB_DESCRIPCION    VARCHAR2(100),
	RPB_TEMI           VARCHAR2(30),                                 --- NO SE LO QUE ES TEMI Y TEMF
	RPB_TEMF           VARCHAR2(30)
);
/


CREATE OR REPLACE TYPE RESUMENHISTORICO AS OBJECT (
    RE_FECHA           DATE                 ,
    RE_HECHO           VARCHAR2(30)                  
);
/

CREATE OR REPLACE TYPE RESULTADOEVALUACION AS OBJECT (
    RES_AÑO            DATE                 ,
    RES_RESULTADO      NUMBER(7)               ,
    RES_POSICION       NUMBER(7)               ,
    RES_IDPRODUCTOR    NUMBER(7)              ,
    RES_RUBRO          VARCHAR2(30)           
);
/


-----NESTED 

CREATE OR REPLACE TYPE COMIDA_NT AS TABLE OF COMIDA;
/

CREATE OR REPLACE TYPE PATROCINIO_NT AS TABLE OF PATROCINIO;
/

CREATE OR REPLACE TYPE DISTRIBUCION_NT AS TABLE OF DISTRIBUCION;
/

CREATE OR REPLACE TYPE FORMAPAGO_NT AS TABLE OF FORMAPAGO;
/

CREATE OR REPLACE TYPE RESULTADOEVALUACION_NT AS TABLE OF RESULTADOEVALUACION;
/

CREATE OR REPLACE TYPE RECETAPROCESOBASICO_NT AS TABLE OF RECETAPROCESOBASICO;
/

CREATE OR REPLACE TYPE RESUMENHISTORICO_NT AS TABLE OF RESUMENHISTORICO;​
/

CREATE OR REPLACE TYPE CONTACTOS_NT AS TABLE OF CONTACTO;
/

-----VARRAY

CREATE OR REPLACE TYPE FORMAS_ENVIO_VA AS VARRAY(6) OF VARCHAR2(30);
/
